package com.ytdl.app.youtube

/** A single video in a search result / channel listing. */
data class VideoItem(
    val id: String,
    val title: String,
    val author: String,
    val channelId: String?,
    val durationSeconds: Long,
    val durationText: String,
    val viewCountText: String,
    val publishedText: String,
    val thumbnailUrl: String,
    val isLive: Boolean,
)

data class ChannelItem(
    val id: String,
    val name: String,
    val thumbnailUrl: String,
    val subscriberText: String,
    val videoCountText: String,
)

data class SearchPage(
    val videos: List<VideoItem>,
    val channels: List<ChannelItem>,
    val continuation: String?,
)

enum class StreamKind { MUXED, VIDEO_ONLY, AUDIO_ONLY }

data class MediaStream(
    val itag: Int,
    val url: String,
    val mimeType: String,
    /** mp4 / webm / m4a / opus */
    val container: String,
    /** avc1 / vp9 / av01 / mp4a / opus */
    val codec: String,
    val kind: StreamKind,
    val qualityLabel: String,
    val height: Int,
    val fps: Int,
    val bitrate: Long,
    val audioSampleRate: Int,
    val contentLength: Long,
) {
    val isVideo: Boolean get() = kind != StreamKind.AUDIO_ONLY
    val isAudio: Boolean get() = kind != StreamKind.VIDEO_ONLY

    /** File extension for a raw, un-muxed save of this stream. */
    val fileExtension: String
        get() = when {
            kind == StreamKind.AUDIO_ONLY && container == "mp4" -> "m4a"
            kind == StreamKind.AUDIO_ONLY && codec.startsWith("opus") -> "opus"
            kind == StreamKind.AUDIO_ONLY -> "webm"
            container == "webm" -> "webm"
            else -> "mp4"
        }
}

data class SubtitleTrack(
    val languageCode: String,
    val name: String,
    val url: String,
    val autoGenerated: Boolean,
)

data class StreamInfo(
    val id: String,
    val title: String,
    val author: String,
    val channelId: String?,
    val durationSeconds: Long,
    val thumbnailUrl: String,
    val viewCount: Long,
    val videoStreams: List<MediaStream>,
    val audioStreams: List<MediaStream>,
    val subtitles: List<SubtitleTrack>,
) {
    /** Video streams grouped so that each height appears once, best variant first. */
    fun videoOptions(preferWebm: Boolean): List<MediaStream> {
        val byHeight = videoStreams.filter { it.height > 0 }.groupBy { it.height }
        return byHeight.entries
            .sortedByDescending { it.key }
            .mapNotNull { (_, list) -> pickBestVariant(list, preferWebm) }
    }

    private fun pickBestVariant(list: List<MediaStream>, preferWebm: Boolean): MediaStream? =
        list.maxWithOrNull(
            compareBy<MediaStream> { containerScore(it, preferWebm) }
                .thenBy { it.fps }
                .thenBy { it.bitrate }
        )

    private fun containerScore(s: MediaStream, preferWebm: Boolean): Int = when {
        // AV1 decodes poorly on many mid-range phones and cannot be muxed into MP4
        // on older Android versions, so it is always the last resort.
        s.codec.startsWith("av01") -> 0
        preferWebm && s.container == "webm" -> 3
        !preferWebm && s.container == "mp4" -> 3
        else -> 2
    }

    fun audioOptions(): List<MediaStream> =
        audioStreams.sortedByDescending { it.bitrate }

    fun bestAudio(preferWebm: Boolean): MediaStream? {
        // AAC in an .m4a container is muxable into MP4 on every supported Android
        // version, so it wins unless the caller explicitly wants WebM/Opus.
        val aac = audioStreams.filter { it.container == "mp4" }.maxByOrNull { it.bitrate }
        val opus = audioStreams.filter { it.container == "webm" }.maxByOrNull { it.bitrate }
        return if (preferWebm) (opus ?: aac) else (aac ?: opus)
    }
}

class ExtractionException(message: String, cause: Throwable? = null) : Exception(message, cause)
