package com.ytdl.app.download

import com.ytdl.app.settings.Quality
import com.ytdl.app.settings.Settings
import com.ytdl.app.youtube.MediaStream
import com.ytdl.app.youtube.StreamInfo
import com.ytdl.app.youtube.StreamKind
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.UUID

/** Turns "this video, that quality" into a concrete [DownloadTask]. */
object DownloadPlanner {

    /**
     * @param videoStream null for an audio-only download.
     */
    fun build(
        info: StreamInfo,
        videoStream: MediaStream?,
        audioStream: MediaStream?,
        settings: Settings,
    ): DownloadTask {
        val audioOnly = videoStream == null
        val alreadyMuxed = videoStream?.kind == StreamKind.MUXED

        // A muxed progressive stream carries its own audio; anything else needs
        // an audio track fetched alongside it.
        val audio = when {
            audioOnly -> audioStream ?: info.bestAudio(settings.preferWebm)
            alreadyMuxed -> null
            else -> audioStream ?: info.bestAudio(settings.preferWebm)
        }

        val quality = when {
            audioOnly -> audio?.qualityLabel.orEmpty()
            else -> videoStream?.qualityLabel.orEmpty()
        }

        val extension = when {
            audioOnly -> audio?.fileExtension ?: "m4a"
            alreadyMuxed -> videoStream?.fileExtension ?: "mp4"
            videoStream?.container == "webm" && audio?.container == "webm" -> "webm"
            else -> "mp4"
        }

        val subtitle = if (settings.downloadSubtitles) {
            val preferred = Locale.getDefault().language
            info.subtitles.firstOrNull { it.languageCode.startsWith(preferred) && !it.autoGenerated }
                ?: info.subtitles.firstOrNull { it.languageCode.startsWith(preferred) }
                ?: info.subtitles.firstOrNull { it.languageCode.startsWith("en") }
                ?: info.subtitles.firstOrNull()
        } else null

        return DownloadTask(
            id = UUID.randomUUID().toString(),
            videoId = info.id,
            title = info.title,
            author = info.author,
            thumbnailUrl = info.thumbnailUrl,
            durationSeconds = info.durationSeconds,

            videoUrl = videoStream?.url,
            videoItag = videoStream?.itag ?: -1,
            videoContainer = videoStream?.container ?: "mp4",
            videoCodec = videoStream?.codec.orEmpty(),
            videoBytes = videoStream?.contentLength ?: 0L,

            audioUrl = audio?.url,
            audioItag = audio?.itag ?: -1,
            audioContainer = audio?.container ?: "mp4",
            audioCodec = audio?.codec.orEmpty(),
            audioBytes = audio?.contentLength ?: 0L,

            alreadyMuxed = alreadyMuxed,
            audioOnly = audioOnly,
            qualityLabel = quality,
            fileName = fileName(settings.filenameTemplate, info, quality),
            fileExtension = extension,

            subtitleUrl = subtitle?.url,
            subtitleLanguage = subtitle?.languageCode.orEmpty(),
            saveThumbnail = settings.saveThumbnail,

            status = DownloadStatus.QUEUED,
            totalBytes = (videoStream?.contentLength ?: 0L) + (audio?.contentLength ?: 0L),
            createdAt = System.currentTimeMillis(),
        )
    }

    /**
     * Picks the stream matching the user's default quality, stepping down to the
     * closest available one when the exact height is not offered.
     */
    fun autoSelectVideo(info: StreamInfo, settings: Settings): MediaStream? {
        val options = info.videoOptions(settings.preferWebm)
        if (options.isEmpty()) return null
        return when (settings.defaultHeight) {
            Quality.BEST, Quality.ASK -> options.first()
            else -> options.firstOrNull { it.height <= settings.defaultHeight } ?: options.last()
        }
    }

    fun autoSelectAudio(info: StreamInfo, settings: Settings): MediaStream? {
        val options = info.audioOptions()
        if (options.isEmpty()) return null
        val target = settings.defaultAudioBitrate
        if (target <= 0) return info.bestAudio(settings.preferWebm) ?: options.first()
        return options.firstOrNull { it.bitrate / 1000 <= target } ?: options.last()
    }

    private fun fileName(template: String, info: StreamInfo, quality: String): String {
        val date = SimpleDateFormat("yyyy-MM-dd", Locale.US).format(Date())
        val filled = template
            .replace("%title%", info.title)
            .replace("%author%", info.author)
            .replace("%quality%", quality)
            .replace("%id%", info.id)
            .replace("%date%", date)
            .ifBlank { info.title }
        return Output.sanitize(filled)
    }
}
